### ISSUE TITLE
vim-runners does not recognize Vim's Python support when dynamically linked.

### ISSUE THREAD

**Issue by ereOn** [okcompute/vim-python-tests-runner#1]
The latest Windows Vim (8.0) isn't compiled with a static Python anymore, but with a dynamic one.

This means `vim --version` returns:

```
+python/dyn
+python3/dyn
```

And so [this check](https://github.com/okcompute/vim-python-tests-runner/blob/master/ftplugin/python/runner.vim#L10) fails but should not:

```
if !has('python')
    echo "Error: Required vim compiled with +python"
    finish
endif
```

Could the check please be fixed ?

**Comment by okcompute** [comment]
Strange. I have been running Vim 8.0 for Windows for a month now and never had this issue. Where did you get your binaries? I have tried the official release and Cream distro. Both did not show the behavior you are exposing on my machine!

**Comment by ereOn** [comment]
I got them from the official Vim page. I agree this is strange since I didn't get the problem at work either.

I'm running Windows 10 here, perhaps that's the difference ?

**Comment by okcompute** [comment]
I don't have Windows 10 myself so I cannot test the plugin in that context. But, on other platforms, the typical causes for this error is either:
1. 32 bits vs. 64 bits. You are trying to use 64 bits Python dll with a 32 bits version of Vim
2. Vim cannot find the python dll. The distro maintainer has activated the `+python` flag when building the release but Vim runtime cannot reach the `pythonxx.dll`.

Could one of these be the cause of your problem (I suspect the second one )?
